-- Your sql code in this file
-- NOTE: Please, don't add sentence to create database in this script file.
--       You can create database locally to test it.
--       Consider add ';' at end sentence.

		/* Se Crea Tabla Employee */
	CREATE TABLE EMPLOYEE(
		ID_EMPLOYEE		integer NOT NULL,		/* ID_EMPLOYEE: CORRESPONDE AL PRIMARE KEY		*/
		ID_DEPARTMENT	integer NOT NULL,		/* ID_DEPARTMENT: CORRESPONDE AL FOREIGN KEY	*/
		FIRST_NAME		varchar(50) NULL,
		LAST_NAME		varchar(50) NULL,
	CONSTRAINT PK_EMPLOYEE PRIMARY KEY (ID_EMPLOYEE) );
	
		/* Se Crea Tabla Employee_Department */
	CREATE TABLE EMPLOYEE_DEPARTMENT(
		ID_DEPARTMENT	integer NOT NULL,		/* ID_DEPARTMENT: CORRESPONDE AL PRIMARE KEY	*/
		NAME			varchar(50) NULL,
		DESCRIPTION		varchar(150) NULL,
	CONSTRAINT PK_EMPLOYEE_DEPARTMENT PRIMARY KEY (ID_DEPARTMENT) );
	
		/* Se hace la modificacion a la tabla EMPLOYEE  para asignarle el Deparment				*/
	ALTER TABLE EMPLOYEE
		ADD CONSTRAINT FK_EMPLOYEE_TO_DEPARTMENT FOREIGN KEY(ID_DEPARTMENT)
		REFERENCES EMPLOYEE_DEPARTMENT (ID_DEPARTMENT)
		on delete restrict on update restrict;

		
		/* INSERCIÓN DE DATOS EN LA BASE DE DATOS												*/
		/* Se inserta datos a la tabla de EMPLOYEE_DEPARTMENT									*/
	insert into EMPLOYEE_DEPARTMENT ( ID_DEPARTMENT, NAME, DESCRIPTION )
		values ( 10, 'DEPART_10', 'DESCRIPTION OF DEPARTMENT_10' );
	insert into EMPLOYEE_DEPARTMENT ( ID_DEPARTMENT, NAME, DESCRIPTION )
		values ( 20, 'DEPART_20', 'DESCRIPTION OF DEPARTMENT_20' );
	insert into EMPLOYEE_DEPARTMENT ( ID_DEPARTMENT, NAME, DESCRIPTION )
		values ( 30, 'DEPART_30', 'DESCRIPTION OF DEPARTMENT_30' );
	insert into EMPLOYEE_DEPARTMENT ( ID_DEPARTMENT, NAME, DESCRIPTION )
		values ( 40, 'DEPART_40', 'DESCRIPTION OF DEPARTMENT_40' );
	insert into EMPLOYEE_DEPARTMENT ( ID_DEPARTMENT, NAME, DESCRIPTION )
		values ( 50, 'DEPART_50', 'DESCRIPTION OF DEPARTMENT_50' );
	insert into EMPLOYEE_DEPARTMENT ( ID_DEPARTMENT, NAME, DESCRIPTION )
		values ( 60, 'DEPART_60', 'DESCRIPTION OF DEPARTMENT_60' );
	
		/* Se inserta datos a la tabla de EMPLOYEE												*/
	insert into EMPLOYEE ( ID_EMPLOYEE, ID_DEPARTMENT, FIRST_NAME, LAST_NAME )
		values (10, 10, 'JUAN', 'CRUZ' );
	insert into EMPLOYEE ( ID_EMPLOYEE, ID_DEPARTMENT, FIRST_NAME, LAST_NAME )
		values (20, 10, 'MARIO', 'SANCHEZ' );
	insert into EMPLOYEE ( ID_EMPLOYEE, ID_DEPARTMENT, FIRST_NAME, LAST_NAME )
		values (30, 20, 'VERONICA', 'ARIAS' );
	insert into EMPLOYEE ( ID_EMPLOYEE, ID_DEPARTMENT, FIRST_NAME, LAST_NAME )
		values (40, 60, 'PABLO', 'PEREZ' );
-- ...
